services:
  postgres:
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=pfktasks
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=pfkuser
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  backend:
volumes:
  postgres_data:
  redis_data: