services:
  postgres:
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=pfktasks
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=pfkuser
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - SERVICES=s3
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
networks:
  backend:
volumes:
  postgres_data:
  redis_data: