services:
  postgres:
    image: 'postgres:16'
    container_name: postgres
    environment:
      - POSTGRES_DB=pfktasks
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=pfkuser
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pfkuser -d pfktasks"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3,ses
      - DEBUG=1
      - AWS_DEFAULT_REGION=eu-west-2
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - HOSTNAME_EXTERNAL=localstack
      - HOSTNAME=localstack
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack:/etc/localstack/init/ready.d
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    networks:
      - backend

networks:
  backend:
volumes:
  postgres_data:
  redis_data: