CREATE TABLE attachment
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name   VARCHAR(255)                             NOT NULL,
    file_path   VARCHAR(255)                             NOT NULL,
    file_type   VARCHAR(255)                             NOT NULL,
    uploaded_at date                                     NOT NULL,
    task_id     INTEGER,
    issue_id    INTEGER,
    author_id   INTEGER                                  NOT NULL,
    CONSTRAINT pk_attachment PRIMARY KEY (id)
);

CREATE TABLE comment
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(255)                             NOT NULL,
    created_at date                                     NOT NULL,
    updated_at date,
    is_edited  BOOLEAN                                  NOT NULL,
    task_id    INTEGER,
    issue_id   INTEGER,
    user_id    INTEGER                                  NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE issue
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255)                             NOT NULL,
    description     VARCHAR(255)                             NOT NULL,
    status          VARCHAR(255)                             NOT NULL,
    priority_status VARCHAR(255)                             NOT NULL,
    project_id      INTEGER,
    reported_by_id  INTEGER,
    assigned_to_id  INTEGER,
    CONSTRAINT pk_issue PRIMARY KEY (id)
);

CREATE TABLE notification
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type       VARCHAR(255)                             NOT NULL,
    message    VARCHAR(255)                             NOT NULL,
    is_read    BOOLEAN                                  NOT NULL,
    created_at date                                     NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);

CREATE TABLE project
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                             NOT NULL,
    description       VARCHAR(255)                             NOT NULL,
    status            VARCHAR(255)                             NOT NULL,
    display_image_url VARCHAR(255)                             NOT NULL,
    owner_id          INTEGER,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE project_collaborators
(
    collaborator_id INTEGER NOT NULL,
    project_id      INTEGER NOT NULL
);

CREATE TABLE task
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                             NOT NULL,
    due_date    date                                     NOT NULL,
    created_at  date                                     NOT NULL,
    priority    VARCHAR(255)                             NOT NULL,
    status      VARCHAR(255)                             NOT NULL,
    project_id  INTEGER,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

CREATE TABLE task_user
(
    task_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL
);

CREATE TABLE users
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token   VARCHAR(255),
    user_id INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_user UNIQUE (user_id);

ALTER TABLE attachment
    ADD CONSTRAINT FK_ATTACHMENT_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE attachment
    ADD CONSTRAINT FK_ATTACHMENT_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES task (id);

ALTER TABLE attachment
    ADD CONSTRAINT FK_ATTACHMENT_ON_TASK FOREIGN KEY (task_id) REFERENCES issue (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES issue (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_TASK FOREIGN KEY (task_id) REFERENCES task (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE issue
    ADD CONSTRAINT FK_ISSUE_ON_ASSIGNED_TO FOREIGN KEY (assigned_to_id) REFERENCES users (id);

ALTER TABLE issue
    ADD CONSTRAINT FK_ISSUE_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE issue
    ADD CONSTRAINT FK_ISSUE_ON_REPORTED_BY FOREIGN KEY (reported_by_id) REFERENCES users (id);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE project_collaborators
    ADD CONSTRAINT fk_procol_on_project FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_collaborators
    ADD CONSTRAINT fk_procol_on_user FOREIGN KEY (collaborator_id) REFERENCES users (id);

ALTER TABLE task_user
    ADD CONSTRAINT fk_task_user_on_task FOREIGN KEY (task_id) REFERENCES task (id);

ALTER TABLE task_user
    ADD CONSTRAINT fk_task_user_on_user FOREIGN KEY (user_id) REFERENCES users (id);